version: "3.9"
name: ej6_vista_prod

networks:
    vista:

services:

    nginx:
        image: nginx:stable
        volumes: 
            - ./html:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        depends_on:
            - php
            - db
        networks:
            - vista

    php:
        build: 
            context: .
            dockerfile: ./Dockerfile-php
        volumes: 
            - ./html:/var/www/html
        ports:
            - 9000:9000
        networks:
            - vista

    db:
        image: mysql:latest
        volumes: 
            - ./db:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=ej6_vista
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
        networks:
            - vista
